// Sample election data used for initial render before Supabase is populated

export const sampleElections = [
    {
        id: '1',
        name_en: 'Federal Election 2024',
        name_np: 'संघीय निर्वाचन २०८१',
        type: 'federal',
        status: 'live',
        description: 'Nationwide representatives selection for the House of Representatives.',
        total_constituencies: 165,
        counted: 82,
        image: '/images/federal.jpg',
    },
    {
        id: '2',
        name_en: 'Provincial Assembly',
        name_np: 'प्रदेश सभा',
        type: 'provincial',
        status: 'verified',
        description: 'Regional governance elections across 7 provinces of Nepal.',
        total_constituencies: 330,
        counted: 330,
        province: 'Bagmati Province',
        image: '/images/provincial.jpg',
    },
    {
        id: '3',
        name_en: 'By-Elections: Kirtipur',
        name_np: 'उप-निर्वाचन: कीर्तिपुर',
        type: 'by-election',
        status: 'upcoming',
        description: 'Vacant local level leadership positions in specialized constituencies.',
        total_constituencies: 3,
        counted: 0,
        date: 'Dec 12, 2024',
        image: '/images/byelection.jpg',
    },
]

export const sampleParties = [
    {
        id: '1',
        name_en: 'Nepali Congress',
        name_np: 'नेपाली काँग्रेस',
        abbreviation: 'NC',
        ideology: 'Center-left • Democratic',
        votes: 3_450_210,
        seats: 62,
        totalSeats: 165,
        color: '#dc2626',
        trend: 1.2,
    },
    {
        id: '2',
        name_en: 'CPN-UML',
        name_np: 'नेकपा एमाले',
        abbreviation: 'UML',
        ideology: 'Center-left • Marxist-Leninist',
        votes: 3_120_445,
        seats: 58,
        totalSeats: 165,
        color: '#2563eb',
        trend: 0.5,
    },
    {
        id: '3',
        name_en: 'CPN-Maoist Centre',
        name_np: 'नेकपा माओवादी केन्द्र',
        abbreviation: 'MC',
        ideology: 'Far-left • Maoist',
        votes: 1_980_112,
        seats: 21,
        totalSeats: 165,
        color: '#ea580c',
        trend: 0.0,
    },
    {
        id: '4',
        name_en: 'Rastriya Swatantra Party',
        name_np: 'राष्ट्रिय स्वतन्त्र पार्टी',
        abbreviation: 'RSP',
        ideology: 'Centrist • Anti-establishment',
        votes: 1_245_670,
        seats: 18,
        totalSeats: 165,
        color: '#7c3aed',
        trend: 4.8,
    },
    {
        id: '5',
        name_en: 'Rastriya Prajatantra Party',
        name_np: 'राष्ट्रिय प्रजातन्त्र पार्टी',
        abbreviation: 'RPP',
        ideology: 'Right-wing • Monarchist',
        votes: 412_300,
        seats: 4,
        totalSeats: 165,
        color: '#0d9488',
        trend: -0.3,
    },
    {
        id: '6',
        name_en: 'Janata Samajbadi Party',
        name_np: 'जनता समाजवादी पार्टी',
        abbreviation: 'JSP',
        ideology: 'Center-left • Federalist',
        votes: 274_164,
        seats: 2,
        totalSeats: 165,
        color: '#16a34a',
        trend: -1.1,
    },
]

export const sampleComments = [
    {
        id: '1',
        anon_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
        content: 'The voter turnout in Kathmandu District 4 seems significantly higher than 2017. Any official figures yet? Watching closely from the booth.',
        created_at: '2024-11-20T12:45:00Z',
        likes: 12,
        replies: [
            {
                id: '1r',
                anon_id: 'official-watcher',
                author_name: 'Election Watcher',
                is_official: true,
                content: 'Official figures for KTM-4 are expected at 5:00 PM. Preliminary data suggests 62% turnout as of noon.',
                created_at: '2024-11-20T12:50:00Z',
            },
        ],
    },
    {
        id: '2',
        anon_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
        content: 'Smooth voting process in Pokhara. The digital verification system is working much faster this time around. Kudos to the Election Commission.',
        created_at: '2024-11-20T12:52:00Z',
        likes: 24,
        replies: [],
    },
    {
        id: '3',
        anon_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
        content: 'Just heard reports of ballot box security issues in Saptari. Can anyone confirm? Stay safe everyone.',
        created_at: '2024-11-20T13:05:00Z',
        likes: 8,
        replies: [],
        flagged: true,
    },
]

export const sampleActivity = [
    {
        id: '1',
        text: 'Gagan Thapa (NC) leading by 4,200 votes in Kathmandu-4 after 80% count.',
        time: 'Just now',
        type: 'result',
    },
    {
        id: '2',
        text: 'Rabi Lamichhane (RSP) wins Chitwan-2 by a margin of 12,500 votes.',
        time: '5 mins ago',
        type: 'winner',
    },
    {
        id: '3',
        text: 'Election commission reports 72% overall turnout in Jhapa districts.',
        time: '12 mins ago',
        type: 'info',
    },
    {
        id: '4',
        text: 'Counting suspended in one booth of Syangja due to technical glitch.',
        time: '24 mins ago',
        type: 'alert',
    },
]

export const dashboardStats = {
    totalVotes: 12_482_901,
    voterTurnout: 71.4,
    turnoutChange: 4.2,
    constituenciesDecided: 82,
    totalConstituencies: 165,
    resultPercentage: 49.7,
}

export const sampleCandidates = [
    {
        id: '1',
        name: 'Sher Bahadur Deuba',
        party: 'Nepali Congress',
        abbreviation: 'NC',
        constituency: 'Dadeldhura-1',
        role: 'Former Prime Minister',
        status: 'incumbent',
        image: null,
    },
    {
        id: '2',
        name: 'KP Sharma Oli',
        party: 'CPN-UML',
        abbreviation: 'UML',
        constituency: 'Jhapa-5',
        role: 'Opposition Leader',
        status: 'leading',
        image: null,
    },
    {
        id: '3',
        name: 'Gagan Thapa',
        party: 'Nepali Congress',
        abbreviation: 'NC',
        constituency: 'Kathmandu-4',
        role: 'Youth Leader',
        status: 'leading',
        image: null,
    },
    {
        id: '4',
        name: 'Rabi Lamichhane',
        party: 'Rastriya Swatantra Party',
        abbreviation: 'RSP',
        constituency: 'Chitwan-2',
        role: 'Party President',
        status: 'newcomer',
        image: null,
    },
    {
        id: '5',
        name: 'P. Kamal Dahal',
        party: 'CPN-Maoist Centre',
        abbreviation: 'MC',
        constituency: 'Gorkha-2',
        role: 'Prime Minister',
        status: 'incumbent',
        image: null,
    },
    {
        id: '6',
        name: 'Dr. CK Raut',
        party: 'Janata Samajbadi Party',
        abbreviation: 'JSP',
        constituency: 'Saptari-2',
        role: 'Regional Leader',
        status: 'leading',
        image: null,
    },
]

export const regionalData = [
    { region: 'Province 1', leader: 'NC', abbreviation: 'NC', percentage: 38 },
    { region: 'Madhesh', leader: 'UML', abbreviation: 'UML', percentage: 42 },
    { region: 'Bagmati', leader: 'NC', abbreviation: 'NC', percentage: 35 },
    { region: 'Gandaki', leader: 'NC', abbreviation: 'NC', percentage: 40 },
    { region: 'Lumbini', leader: 'UML', abbreviation: 'UML', percentage: 44 },
    { region: 'Karnali', leader: 'MC', abbreviation: 'MC', percentage: 36 },
    { region: 'Sudurpashchim', leader: 'NC', abbreviation: 'NC', percentage: 39 },
]
