// Sample election data used for initial render before Supabase is populated
// Also includes party leaders, PM data, and election countdown info

export const ELECTION_DATE = new Date('2026-03-05T05:00:00+05:45') // Nepal Election 2082 BS – March 5, 2026 at 5 AM NPT
export const MAJORITY_SEATS = 138 // Required for government formation

export const sampleElections = [
    {
        id: '1',
        name_en: 'Federal Election 2082',
        name_np: 'संघीय निर्वाचन २०८२',
        type: 'federal',
        status: 'upcoming',
        description: 'Nationwide representatives selection for the House of Representatives.',
        total_constituencies: 165,
        counted: 0,
        image: '/images/federal.jpg',
    },
    {
        id: '2',
        name_en: 'Provincial Assembly',
        name_np: 'प्रदेश सभा',
        type: 'provincial',
        status: 'upcoming',
        description: 'Regional governance elections across 7 provinces of Nepal.',
        total_constituencies: 330,
        counted: 0,
        province: 'All Provinces',
        image: '/images/provincial.jpg',
    },
]

export const sampleParties = [
    {
        id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        name_en: 'Nepali Congress',
        name_np: 'नेपाली काँग्रेस',
        abbreviation: 'NC',
        ideology: 'Center-left • Democratic Socialism',
        votes: 0,
        seats: 0,
        totalSeats: 165,
        color: '#dc2626',
        trend: 0,
    },
    {
        id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
        name_en: 'CPN-UML',
        name_np: 'नेकपा एमाले',
        abbreviation: 'UML',
        ideology: 'Marxist-Leninist • Left',
        votes: 0,
        seats: 0,
        totalSeats: 165,
        color: '#2563eb',
        trend: 0,
    },
    {
        id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
        name_en: 'CPN-Maoist Centre',
        name_np: 'नेकपा माओवादी केन्द्र',
        abbreviation: 'MC',
        ideology: 'Far-left • Maoist',
        votes: 0,
        seats: 0,
        totalSeats: 165,
        color: '#ea580c',
        trend: 0,
    },
    {
        id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
        name_en: 'Rastriya Swatantra Party',
        name_np: 'राष्ट्रिय स्वतन्त्र पार्टी',
        abbreviation: 'RSP',
        ideology: 'Centrist • Anti-establishment',
        votes: 0,
        seats: 0,
        totalSeats: 165,
        color: '#7c3aed',
        trend: 0,
    },
    {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
        name_en: 'Rastriya Prajatantra Party',
        name_np: 'राष्ट्रिय प्रजातन्त्र पार्टी',
        abbreviation: 'RPP',
        ideology: 'Right-wing • Hindu Nationalism',
        votes: 0,
        seats: 0,
        totalSeats: 165,
        color: '#0d9488',
        trend: 0,
    },
    {
        id: 'ffffffff-ffff-ffff-ffff-ffffffffffff',
        name_en: 'Janata Samajbadi Party',
        name_np: 'जनता समाजवादी पार्टी',
        abbreviation: 'JSP',
        ideology: 'Federalist • Social Democrat',
        votes: 0,
        seats: 0,
        totalSeats: 165,
        color: '#16a34a',
        trend: 0,
    },
]

export const partyLeaders = [
    {
        id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        name_en: 'Nepali Congress',
        name_np: 'नेपाली काँग्रेस',
        abbreviation: 'NC',
        color: '#dc2626',
        ideology: 'Center-left • Democratic Socialism',
        leader: 'Gagan Thapa',
        leader_np: 'गगन थापा',
        leader_title: 'General Secretary',
        founded: 1947,
        seats: 0,
        previous_seats: 89,
        symbol: '🌳',
    },
    {
        id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
        name_en: 'CPN-UML',
        name_np: 'नेकपा एमाले',
        abbreviation: 'UML',
        color: '#2563eb',
        ideology: 'Marxist-Leninist • Left',
        leader: 'KP Sharma Oli',
        leader_np: 'केपी शर्मा ओली',
        leader_title: 'Chairman',
        founded: 1991,
        seats: 0,
        previous_seats: 78,
        symbol: '☀️',
    },
    {
        id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
        name_en: 'CPN-Maoist Centre',
        name_np: 'नेकपा माओवादी केन्द्र',
        abbreviation: 'MC',
        color: '#ea580c',
        ideology: 'Far-left • Maoist',
        leader: 'Pushpa Kamal Dahal',
        leader_np: 'पुष्पकमल दाहाल',
        leader_title: 'Chairman (Prachanda)',
        founded: 1994,
        seats: 0,
        previous_seats: 32,
        symbol: '🔨',
    },
    {
        id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
        name_en: 'Rastriya Swatantra Party',
        name_np: 'राष्ट्रिय स्वतन्त्र पार्टी',
        abbreviation: 'RSP',
        color: '#7c3aed',
        ideology: 'Centrist • Anti-establishment',
        leader: 'Rabi Lamichhane',
        leader_np: 'रवि लामिछाने',
        leader_title: 'Chairman',
        founded: 2022,
        seats: 0,
        previous_seats: 20,
        symbol: '🗽',
    },
    {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
        name_en: 'Rastriya Prajatantra Party',
        name_np: 'राष्ट्रिय प्रजातन्त्र पार्टी',
        abbreviation: 'RPP',
        color: '#0d9488',
        ideology: 'Right-wing • Hindu Nationalism',
        leader: 'Rajendra Lingden',
        leader_np: 'राजेन्द्र लिङ्देन',
        leader_title: 'Chairman',
        founded: 1990,
        seats: 0,
        previous_seats: 14,
        symbol: '👑',
    },
    {
        id: 'ffffffff-ffff-ffff-ffff-ffffffffffff',
        name_en: 'Janata Samajbadi Party',
        name_np: 'जनता समाजवादी पार्टी',
        abbreviation: 'JSP',
        color: '#16a34a',
        ideology: 'Federalist • Social Democrat',
        leader: 'Upendra Yadav',
        leader_np: 'उपेन्द्र यादव',
        leader_title: 'Chairman',
        founded: 2020,
        seats: 0,
        previous_seats: 12,
        symbol: '🏛️',
    },
    {
        id: '11111111-aaaa-bbbb-cccc-dddddddddddd',
        name_en: 'Loktantrik Samajwadi Party',
        name_np: 'लोकतान्त्रिक समाजवादी पार्टी',
        abbreviation: 'LSP',
        color: '#f59e0b',
        ideology: 'Center-left • Federal',
        leader: 'Mahantha Thakur',
        leader_np: 'महन्थ ठाकुर',
        leader_title: 'Chairman',
        founded: 2017,
        seats: 0,
        previous_seats: 4,
        symbol: '⚖️',
    },
    {
        id: '22222222-aaaa-bbbb-cccc-dddddddddddd',
        name_en: 'Janamat Party',
        name_np: 'जनमत पार्टी',
        abbreviation: 'JP',
        color: '#8b5cf6',
        ideology: 'Populist • Regional',
        leader: 'CK Raut',
        leader_np: 'सीके राउत',
        leader_title: 'Chairman',
        founded: 2019,
        seats: 0,
        previous_seats: 6,
        symbol: '✊',
    },
]

export const sampleCandidates = [
    {
        id: '1',
        name: 'Gagan Thapa',
        name_np: 'गगन थापा',
        party: 'Nepali Congress',
        abbreviation: 'NC',
        color: '#dc2626',
        constituency: 'Sarlahi-4',
        role: 'General Secretary • Youth Leader',
        status: 'contesting',
        symbol: '🌳',
    },
    {
        id: '2',
        name: 'KP Sharma Oli',
        name_np: 'केपी शर्मा ओली',
        party: 'CPN-UML',
        abbreviation: 'UML',
        color: '#2563eb',
        constituency: 'Jhapa-5',
        role: 'Current Prime Minister',
        status: 'contesting',
        symbol: '☀️',
    },
    {
        id: '3',
        name: 'Gagan Thapa',
        name_np: 'गगन थापा',
        party: 'Nepali Congress',
        abbreviation: 'NC',
        color: '#dc2626',
        constituency: 'Kathmandu-4',
        role: 'General Secretary • Youth Leader',
        status: 'contesting',
        symbol: '🌳',
    },
    {
        id: '4',
        name: 'Rabi Lamichhane',
        name_np: 'रवि लामिछाने',
        party: 'Rastriya Swatantra Party',
        abbreviation: 'RSP',
        color: '#7c3aed',
        constituency: 'Chitwan-2',
        role: 'Party Chairman • Former DIG',
        status: 'contesting',
        symbol: '🗽',
    },
    {
        id: '5',
        name: 'Pushpa Kamal Dahal',
        name_np: 'पुष्पकमल दाहाल (प्रचण्ड)',
        party: 'CPN-Maoist Centre',
        abbreviation: 'MC',
        color: '#ea580c',
        constituency: 'Gorkha-2',
        role: 'Chairman • Former PM (Prachanda)',
        status: 'contesting',
        symbol: '🔨',
    },
    {
        id: '6',
        name: 'Rajendra Lingden',
        name_np: 'राजेन्द्र लिङ्देन',
        party: 'Rastriya Prajatantra Party',
        abbreviation: 'RPP',
        color: '#0d9488',
        constituency: 'Jhapa-4',
        role: 'Party Chairman',
        status: 'contesting',
        symbol: '👑',
    },
    {
        id: '7',
        name: 'Upendra Yadav',
        name_np: 'उपेन्द्र यादव',
        party: 'Janata Samajbadi Party',
        abbreviation: 'JSP',
        color: '#16a34a',
        constituency: 'Saptari-3',
        role: 'Party Chairman • Madhesh Leader',
        status: 'contesting',
        symbol: '🏛️',
    },
    {
        id: '8',
        name: 'CK Raut',
        name_np: 'सीके राउत',
        party: 'Janamat Party',
        abbreviation: 'JP',
        color: '#8b5cf6',
        constituency: 'Saptari-2',
        role: 'Party Chairman • Regional Leader',
        status: 'contesting',
        symbol: '✊',
    },
]

export const sampleComments = [
    {
        id: '1',
        anon_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
        content: 'Election 2082 is going to be historic. Which party do you think will get the most seats?',
        created_at: new Date().toISOString(),
        likes: 0,
        replies: [],
    },
]

export const sampleActivity = [
    {
        id: '1',
        text: 'Federal Election 2082 counting date to be announced by Election Commission Nepal.',
        time: 'Coming Soon',
        type: 'info',
    },
    {
        id: '2',
        text: '165 constituencies prepared across 7 provinces for the upcoming election.',
        time: 'Preparation',
        type: 'info',
    },
    {
        id: '3',
        text: 'All major parties have announced their candidates for key constituencies.',
        time: 'Update',
        type: 'info',
    },
    {
        id: '4',
        text: 'Voter registration underway — Election Commission urges all eligible citizens to register.',
        time: 'Ongoing',
        type: 'info',
    },
]

export const dashboardStats = {
    totalVotes: 0,
    voterTurnout: 0,
    turnoutChange: 0,
    constituenciesDecided: 0,
    totalConstituencies: 165,
    resultPercentage: 0,
}

export const provinces = [
    { number: 1, name: 'Koshi', name_np: 'कोशी', constituencies: 28 },
    { number: 2, name: 'Madhesh', name_np: 'मधेश', constituencies: 23 },
    { number: 3, name: 'Bagmati', name_np: 'बागमती', constituencies: 35 },
    { number: 4, name: 'Gandaki', name_np: 'गण्डकी', constituencies: 17 },
    { number: 5, name: 'Lumbini', name_np: 'लुम्बिनी', constituencies: 25 },
    { number: 6, name: 'Karnali', name_np: 'कर्णाली', constituencies: 13 },
    { number: 7, name: 'Sudurpashchim', name_np: 'सुदूरपश्चिम', constituencies: 16 },
]

export const pmHistory = [
    { name: 'KP Sharma Oli', party: 'UML', term: '2024-present', color: '#2563eb' },
    { name: 'Pushpa Kamal Dahal', party: 'MC', term: '2022-2024', color: '#ea580c' },
    { name: 'Gagan Thapa', party: 'NC', term: 'NC Leader', color: '#dc2626' },
    { name: 'KP Sharma Oli', party: 'UML', term: '2018-2021', color: '#2563eb' },
]

export const regionalData = [
    { region: 'Koshi', leader: 'NC', abbreviation: 'NC', percentage: 0 },
    { region: 'Madhesh', leader: 'UML', abbreviation: 'UML', percentage: 0 },
    { region: 'Bagmati', leader: 'NC', abbreviation: 'NC', percentage: 0 },
    { region: 'Gandaki', leader: 'NC', abbreviation: 'NC', percentage: 0 },
    { region: 'Lumbini', leader: 'UML', abbreviation: 'UML', percentage: 0 },
    { region: 'Karnali', leader: 'MC', abbreviation: 'MC', percentage: 0 },
    { region: 'Sudurpashchim', leader: 'NC', abbreviation: 'NC', percentage: 0 },
]
